### PR TITLE
Display content types for responses correctly

### LINKED ISSUE #1762: Content-type for request and response body should be treated independently
### Context
I have the following POST method specified in RAML that has an URL encoded body for the request, but a JSON body for the response:

```yaml
post:
  body:
    application/x-www-form-urlencoded:
      type: ProductSearchParameter
      (builtinType): object

  responses:
    200:
      body:
        application/json:
          type: ProductProjectionPagedSearchResponse
          (builtinType): object

```
### Current behavior

The Kit renders the content type for this endpoint correctly for the request as  `application/x-www-form-urlencoded`, but not for the response:
wrong response content type
### Expected behavior
The response should show `application/json` instead of  `application/x-www-form-urlencoded`.

### PR DESCRIPTION
**Pull request by timonrey**
closes #1762

### CODE REVIEW

File: packages/gatsby-theme-api-docs/src/components/resource/method/request-response-examples.js [hunk 1]
```diff
@@ -9,9 +9,9 @@ const RequestResponseExamples = (props) => {
   const apiTypes = useApiTypes();
   const responsesCodeExamples = [];
   if (props.responses) {
-    props.responses.forEach((response) => {
+    props.responses.forEach((response, index) => {
       const typeDisplayName =
-        response.body && response.body.applicationjson.type;
+        response.body && response.body[props.contentType[index]].type;
```
Comment (gabriele-ct) [inline packages/gatsby-theme-api-docs/src/components/resource/method/request-response-examples.js:14]: what if this expression is undefined? `body[props.contentType[index]]`
Also, you can use the [conditional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) instead of repeating `response.body && ....`

So it would become `response?.body?.[props.contentType[index]]?.type`

File: packages/gatsby-theme-api-docs/src/components/resource/method/request-response-examples.js [hunk 2]
```diff
@@ -33,7 +34,7 @@ const RequestResponseExamples = (props) => {
               value: example.value,
             });
           });
-        } else if (apiType.examples && apiType.examples.length > 0) {
+        } else if (apiType?.examples && apiType?.examples.length > 0) {
```
Comment (gabriele-ct) [inline packages/gatsby-theme-api-docs/src/components/resource/method/request-response-examples.js:37]: here too, it could be simply `apiType?.examples?.length > 0`

File: packages/gatsby-theme-api-docs/src/components/resource/method/responses.js [hunk 3]
```diff
@@ -48,16 +50,16 @@ const Responses = ({ apiKey, responses, contentType }) => {
                   <SpacingsInline alignItems="center">
                     {renderTypeAsLink(
                       apiKey,
-                      response.body.applicationjson.type,
+                      response.body[contentType[index]].type,
```
Comment (gabriele-ct) [inline packages/gatsby-theme-api-docs/src/components/resource/method/responses.js:53]: some conditional check here are probably also good to have

**Review by gabriele-ct — CHANGES_REQUESTED** [review]
Just few safety check to be added
