### PR TITLE
Render cards without external link icon

### LINKED ISSUE #1291: Cards with external links: layout broken in certain scenario
This scenario of having a card with an external link does break the layout.  Cards would not have any indication that they are pointing to an external location,  except in the text link. 

Bildschirmfoto 2022-05-09 um 15 16 24

### PR DESCRIPTION
**Pull request by timonrey**
closes #1291 

Now cards with external links won't render the external link icon anymore. It appears only next to textlinks.

### CODE REVIEW

**Review by nkuehn — APPROVED** [review]

**Comment by nkuehn** [comment]
@timonrey  nice, thanks.  Just something broken with the links now.  I hope it's not a bug but just a thing with the test data.

File: packages/gatsby-theme-docs/src/components/card.js [hunk 1]
```diff
@@ -86,13 +86,9 @@ const Card = (props) => (
...
-                    {props.clickable ? (
-                      props.textLink
-                    ) : (
-                      <GatsbyLink href={props.href} noUnderline>
-                        {props.textLink}
-                      </GatsbyLink>
-                    )}
+                    <GatsbyLink href={props.href} noUnderline>
+                      {props.textLink}
+                    </GatsbyLink>
```
Comment (nkuehn) [inline packages/gatsby-theme-docs/src/components/card.js:91]: You should not do HTML that nests links, they are illegal since HTML 5

`<a href="foo">  ....   <a href="foo">  ...  </a>  ... </a>`
