### PR TITLE
Fix beta tag spacing in lists with link entries

### LINKED ISSUE #1813: Spacing between list items when Beta tag is used in lists
Looks like when a Beta tag is used in a list, the span margin is causing significant spacing between list items? Issue can be found [here](https://docs.commercetools.com/api/projects/types#list-of-customizable-data-types).

Screenshot

### PR DESCRIPTION
**Pull request by timonrey**
closes #1813

### CODE REVIEW

File: packages/ui-kit/src/components/markdown.tsx [hunk 1]
```diff
@@ -136,6 +135,12 @@ const Li = styled.li`
   > ul {
     list-style-type: circle;
   }
+  > * + :not(span) {
```
Comment (gabriele-ct) [inline packages/ui-kit/src/components/markdown.tsx:138]: This style change will affect any span tag and it might create undesired side effects
What you could to is specify a className in the PlanTag component and then change the negative rule to target just that specific span 

e.g.
```
> * + :not(span.planTag) {
```

**Review by gabriele-ct — CHANGES_REQUESTED** [review]

File: packages/ui-kit/src/components/markdown.tsx (hunk 1 above)
Comment (timonrey) [reply packages/ui-kit/src/components/markdown.tsx]: Good idea, thank you :)

**Review by gabriele-ct — APPROVED** [review]
👍
