### PR TITLE
fix(theme): prefer overflow: auto

### LINKED ISSUE #59: theme:  main container always has scrollbar
The main container y  overflow is not set to auto, so when on windows or having a mouse attached the scrollbar is visible independently of whether it's needed. 

From a windows user perspective that's perceived as a bug because it deviates from the 99% convention how websites behave.

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #59

### CODE REVIEW

File: packages/gatsby-theme-docs/src/layouts/internals/globals.js [hunk 1]
```diff
@@ -90,23 +89,10 @@ const Globals = () => (
         margin: 0;
         padding: 0;
       }
-      .gatsby-highlight pre[class*='language-'].line-numbers {
```
Comment (emmenko) [inline packages/gatsby-theme-docs/src/layouts/internals/globals.js]: Unrelated cleanup changes...
