### PR TITLE
fix(theme): proptype warnings and mapping of some md elements

### LINKED ISSUE #381: DOM errors in development
5 errors are logged in the browser during development:

Screenshot 2020-04-20 at 17 34 56

I think the problem may have been from the implementation of [markdownFragmentToReact](https://github.com/commercetools/commercetools-docs-kit/blob/master/packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js) in this [PR](https://github.com/commercetools/commercetools-docs-kit/pull/375).

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #381

### CODE REVIEW

File: packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js [hunk 1]
```diff
@@ -43,7 +50,9 @@ const markdownFragmentToReact = (markdownString) =>
         dl: components.dl,
         dt: components.dt,
         dd: components.dd,
-        table: components.p,
+        table: Div,
+        thead: Div,
+        tbody: Div,
```
Comment (emmenko) [inline packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js:55]: Otherwise we get DOM warnings about wrong descendant of `p`

File: packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js [hunk 2]
```diff
@@ -1,10 +1,17 @@
...
 import unified from 'unified';
 import filter from 'unist-util-filter';
 import markdown from 'remark-parse';
 import remark2react from 'remark-react';
 import frontmatter from 'remark-frontmatter';
+import { designSystem } from '@commercetools-docs/ui-kit';
 import components from '../markdown-components';
 
+const Div = styled.div``;
+const Heading = styled.p`
```
Comment (emmenko) [inline packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js:11]: It should be wrapped to a paragraph I think, so that it's rendered as a block.

File: packages/ui-kit/src/components/markdown.js [hunk 3]
```diff
@@ -147,10 +147,14 @@ const Table = styled.table`
...
-        (elem) => elem.props.mdxType === 'thead'
+        (elem) => elem.type === 'thead' || elem.props.mdxType === 'thead'
       );
+      if (!tableHeaders) return null;
       const rowHeaders = tableHeaders.props.children;
-      return React.Children.toArray(rowHeaders.props.children).reduce(
+      const rowHeadersChildren = Array.isArray(rowHeaders)
+        ? rowHeaders
+        : rowHeaders.props.children;
+      return React.Children.toArray(rowHeadersChildren).reduce(
```
Comment (emmenko) [inline packages/ui-kit/src/components/markdown.js:157]: Just to have more safe guards, as I bumped into some issues when trying to render the table with the `markdown-fragment-to-react` function
