### PR TITLE
fix: query parameters types that are objects now render as links

### LINKED ISSUE #322: Types of properties of query parameters should be rendered as link
Current situation on category import when import api is run locally:

Screenshot 2020-03-25 at 16 44 56

`ProcessingState` should be rendered as a link.

### PR DESCRIPTION
**Pull request by davifantasia**
Fixes #322

### CODE REVIEW

File: packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js [hunk 1]
```diff
@@ -13,17 +12,11 @@ const NameType = ({
...
 }) => {
-  const typeLocations = useTypeLocations();
-  const dataForTypeToLinkTo =
-    property.type === 'array' && property.items
-      ? { type: property.items.type, displayPrefix: 'Array of ' }
-      : { type: property.type, displayPrefix: '' };
-
-  const type = renderTypeAsLink(
+  const typeToRender = generateTypeToRender({
+    typeLocations: useTypeLocations(),
```
Comment (emmenko) [inline packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js]: Please keep usage of react hooks within the body function, otherwise it's confusing and might lead to unnecessary issues (for example render a hook within a condition).

```suggestion
  const typeLocations = useTypeLocations();
  const typeToRender = generateTypeToRender({
    typeLocations,
```

File: packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js [hunk 2]
```diff
@@ -39,8 +32,15 @@ const NameType = ({
...
-        <span className="name">{dataForTypeToLinkTo.displayPrefix}</span>
-        {typeof type === 'string' ? <span className="name">{type}</span> : type}
+        {typeToRender.displayPrefix && (
+          <span className="name">{typeToRender.displayPrefix}</span>
+        )}
+
+        {typeof typeToRender.type === 'string' ? (
+          <span className="name">{typeToRender.type}</span>
+        ) : (
+          typeToRender.type
```
Comment (emmenko) [inline packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js]: I'm confused. If `typeToRender.type` is not a string, what can it be?

Comment (davifantasia) [reply packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js]: A `<Link/>`

Comment (emmenko) [reply packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js]: I see...kind of confusing by whatever
